apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-e -X -Dmaven.test.skip=true --no-transfer-progress package"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: settings-xml
  source:
    git:
      url: https://github.com/fbehrens51/tanzu-java-web-app.git
      ref:
        branch: poc


